#!/usr/bin/python
import sys
from extDetect import Extentions
from Imgmain import Imgmain

if __name__ == "__main__":

    if Extentions(sys.argv).CanConversion() == True:
        Imgmain(sys.argv[1]).imgmain()
